spring.application.name=collaborative-editor

spring.h2.console.enabled=true
# --- Production (Postgres), uncomment to use: ---
spring.datasource.url=jdbc:postgresql://localhost:5432/googledocs
spring.datasource.username=postgres
spring.datasource.password=b302Kumar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
